### ISSUE TITLE
Do you have open-source code that can run on the Ubuntu operating system?

### ISSUE THREAD

**Issue by HuydoFlydinotech** [phanxuanquang/AskDB#1]
It would be fantastic to have a version that can run on the Ubuntu operating system.

**Comment by phanxuanquang** [comment]
I do not have any experience with other OSs but Windows, so it is impossible for me to do it. However, I use .NET 8 for my product and it does support Ubuntu/Linux, so you can build a version for your OS based on the libraries I built (Helper, GenAI, DatabaseAnalyzer).
Let's wait for a version for other OSs from the community.
